import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed-variant": "#474647",
        secondary: "#ba002a",
        "on-tertiary-fixed": "#1b1b1c",
        "on-surface": "#1b1d0e",
        "inverse-surface": "#303221",
        "on-tertiary-container": "#aba9aa",
        "surface-dim": "#dbdcc3",
        "surface-tint": "#31628d",
        "surface-container-highest": "#e4e4cc",
        "tertiary-fixed": "#e5e2e3",
        "on-primary-fixed-variant": "#114a73",
        "primary-container": "#00416a",
        "inverse-primary": "#9ccbfb",
        error: "#ba1a1a",
        "on-tertiary": "#ffffff",
        "tertiary-fixed-dim": "#c8c6c7",
        "secondary-container": "#e0273f",
        "tertiary-container": "#3e3e3f",
        tertiary: "#282829",
        "on-secondary-fixed": "#410008",
        "inverse-on-surface": "#f2f2d9",
        background: "#fbfbe2",
        "paper-cream": "#F5F5DC",
        "surface-container": "#efefd7",
        "on-primary": "#ffffff",
        "on-primary-container": "#7faddc",
        "on-error-container": "#93000a",
        surface: "#fbfbe2",
        "primary-fixed-dim": "#9ccbfb",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed-variant": "#92001f",
        "ink-black": "#1A1A1B",
        primary: "#002a48",
        "error-container": "#ffdad6",
        "stamp-red": "#C60C30",
        "on-surface-variant": "#42474e",
        outline: "#72777f",
        "postmark-gray": "#A6A697",
        "airmail-blue": "#00416A",
        "on-secondary-container": "#fffbff",
        "outline-variant": "#c2c7cf",
        "primary-fixed": "#cfe5ff",
        "on-background": "#1b1d0e",
        "surface-variant": "#e4e4cc",
        "surface-container-high": "#eaead1",
        "surface-container-low": "#f5f5dc",
        "on-secondary": "#ffffff",
        "surface-bright": "#fbfbe2",
        "secondary-fixed-dim": "#ffb3b2",
        "on-primary-fixed": "#001d33",
        "secondary-fixed": "#ffdad9",
        "on-error": "#ffffff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "margin-mobile": "16px",
        gutter: "16px",
        "margin-desktop": "32px",
        "container-max": "640px",
        unit: "4px",
      },
      fontFamily: {
        "body-lg": ["var(--font-courier-prime)", "Courier Prime"],
        "label-caps": ["var(--font-jetbrains-mono)", "JetBrains Mono"],
        "headline-lg-mobile": ["var(--font-space-mono)", "Space Mono"],
        "headline-md": ["var(--font-space-mono)", "Space Mono"],
        metadata: ["var(--font-jetbrains-mono)", "JetBrains Mono"],
        "body-md": ["var(--font-courier-prime)", "Courier Prime"],
        "headline-lg": ["var(--font-space-mono)", "Space Mono"],
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-caps": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "700" },
        ],
        "headline-lg-mobile": [
          "20px",
          { lineHeight: "28px", fontWeight: "700" },
        ],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "700" }],
        metadata: ["11px", { lineHeight: "14px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-lg": [
          "24px",
          { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
      },
    },
  },
  plugins: [],
};

export default config;
